// New hand-authored module -- not generated by mcpify, so this file does
// not carry the "generated by mcpify. Do not hand-edit." header every
// other `.rs` file in this crate has.

use rmcp::handler::server::wrapper::Parameters;
use rmcp::model::{PromptMessage, Role};
use rmcp::{prompt, prompt_router};

use crate::core::mcp_server::McpifyServer;
use crate::prompts::{
    BackupRestoreArgs, MasterWorkflowArgs, PermissionsRestrictionsArgs, SpaceProvisioningArgs,
    UserLifecycleArgs, render_context_header,
};

#[prompt_router(vis = "pub(crate)")]
impl McpifyServer {
    #[prompt(
        name = "confluence_workflow",
        description = "Start here. Presents the available Confluence Data Center management \
                        workflows, routes to the right guided sub-workflow based on the user's \
                        goal, and -- where the environment supports it -- delegates that whole \
                        sub-workflow to an isolated sub-task to spare this conversation's \
                        context window."
    )]
    async fn confluence_workflow_prompt(
        &self,
        Parameters(args): Parameters<MasterWorkflowArgs>,
    ) -> Vec<PromptMessage> {
        let header = render_context_header(&[("goal", args.goal.as_deref())]);
        vec![PromptMessage::new_text(
            Role::User,
            format!("{header}\n\n{}", include_str!("content/master.md")),
        )]
    }

    #[prompt(
        name = "confluence_workflow_permissions_restrictions",
        description = "Guided setup of content-level view/update restrictions vs. \
                        space-level (or global) permission grants, including the \
                        read-before-write merge required by restrictions' replace-all \
                        semantics."
    )]
    async fn confluence_workflow_permissions_restrictions_prompt(
        &self,
        Parameters(args): Parameters<PermissionsRestrictionsArgs>,
    ) -> Vec<PromptMessage> {
        let header = render_context_header(&[
            ("content_id", args.content_id.as_deref()),
            ("space_key", args.space_key.as_deref()),
            ("principal_type", args.principal_type.as_deref()),
            ("principal_name", args.principal_name.as_deref()),
        ]);
        vec![PromptMessage::new_text(
            Role::User,
            format!(
                "{header}\n\n{}",
                include_str!("content/permissions_restrictions.md")
            ),
        )]
    }

    #[prompt(
        name = "confluence_workflow_spaces",
        description = "Space lifecycle: create (regular/private/personal), get/update/delete, \
                        archive, restore, trash, categories, per-space color scheme."
    )]
    async fn confluence_workflow_spaces_prompt(&self) -> Vec<PromptMessage> {
        vec![PromptMessage::new_text(
            Role::User,
            include_str!("content/spaces.md"),
        )]
    }

    #[prompt(
        name = "confluence_workflow_content",
        description = "Pages/blog posts: create (top-level vs child vs blueprint draft), \
                        get/update/delete, hierarchy (children/descendants), history, \
                        comments (as a content type), body-format conversion."
    )]
    async fn confluence_workflow_content_prompt(&self) -> Vec<PromptMessage> {
        vec![PromptMessage::new_text(
            Role::User,
            include_str!("content/content.md"),
        )]
    }

    #[prompt(
        name = "confluence_workflow_attachments",
        description = "Upload/list/update/delete attachments, versions, extracted text, \
                        move between content."
    )]
    async fn confluence_workflow_attachments_prompt(&self) -> Vec<PromptMessage> {
        vec![PromptMessage::new_text(
            Role::User,
            include_str!("content/attachments.md"),
        )]
    }

    #[prompt(
        name = "confluence_workflow_labels",
        description = "List/add/delete labels on content and spaces, popular/recent/related \
                        labels."
    )]
    async fn confluence_workflow_labels_prompt(&self) -> Vec<PromptMessage> {
        vec![PromptMessage::new_text(
            Role::User,
            include_str!("content/labels.md"),
        )]
    }

    #[prompt(
        name = "confluence_workflow_properties",
        description = "Generic key/value metadata CRUD, both on content and on spaces (same \
                        shape, parallel endpoint families)."
    )]
    async fn confluence_workflow_properties_prompt(&self) -> Vec<PromptMessage> {
        vec![PromptMessage::new_text(
            Role::User,
            include_str!("content/properties.md"),
        )]
    }

    #[prompt(
        name = "confluence_workflow_users_groups",
        description = "User lifecycle (incl. site-admin provisioning), group lifecycle and \
                        membership (nested/ancestor/parent), user-group assignment."
    )]
    async fn confluence_workflow_users_groups_prompt(&self) -> Vec<PromptMessage> {
        vec![PromptMessage::new_text(
            Role::User,
            include_str!("content/users_groups.md"),
        )]
    }

    #[prompt(
        name = "confluence_workflow_search_cql",
        description = "CQL content search vs general entity search, query construction \
                        guidance, pagination."
    )]
    async fn confluence_workflow_search_cql_prompt(&self) -> Vec<PromptMessage> {
        vec![PromptMessage::new_text(
            Role::User,
            include_str!("content/search_cql.md"),
        )]
    }

    #[prompt(
        name = "confluence_workflow_watches",
        description = "Content and space watch subscriptions (check/add/remove, per-resource \
                        watcher listing)."
    )]
    async fn confluence_workflow_watches_prompt(&self) -> Vec<PromptMessage> {
        vec![PromptMessage::new_text(
            Role::User,
            include_str!("content/watches.md"),
        )]
    }

    #[prompt(
        name = "confluence_workflow_backup_restore",
        description = "Site- or space-scoped definitions backup/restore, async job creation, \
                        polling job status, downloading the result."
    )]
    async fn confluence_workflow_backup_restore_prompt(
        &self,
        Parameters(args): Parameters<BackupRestoreArgs>,
    ) -> Vec<PromptMessage> {
        let header = render_context_header(&[
            ("scope", args.scope.as_deref()),
            ("space_key", args.space_key.as_deref()),
        ]);
        vec![PromptMessage::new_text(
            Role::User,
            format!("{header}\n\n{}", include_str!("content/backup_restore.md")),
        )]
    }

    #[prompt(
        name = "confluence_workflow_webhooks",
        description = "Webhook lifecycle: create, test, inspect invocation \
                        history/statistics, update, delete."
    )]
    async fn confluence_workflow_webhooks_prompt(&self) -> Vec<PromptMessage> {
        vec![PromptMessage::new_text(
            Role::User,
            include_str!("content/webhooks.md"),
        )]
    }

    #[prompt(
        name = "confluence_workflow_admin_diagnostics",
        description = "Thin pointer to the right read-only or maintenance signal \
                        (reindex/unindex, cluster node status, audit records, access mode, \
                        instance metrics, server information, global color scheme)."
    )]
    async fn confluence_workflow_admin_diagnostics_prompt(&self) -> Vec<PromptMessage> {
        vec![PromptMessage::new_text(
            Role::User,
            include_str!("content/admin_diagnostics.md"),
        )]
    }

    #[prompt(
        name = "confluence_workflow_space_provisioning",
        description = "Guided end-to-end setup of a new team space: create (regular/private/\
                        personal fork), grant initial permissions, categorize, optionally \
                        seed a home page."
    )]
    async fn confluence_workflow_space_provisioning_prompt(
        &self,
        Parameters(args): Parameters<SpaceProvisioningArgs>,
    ) -> Vec<PromptMessage> {
        let header = render_context_header(&[
            ("space_key", args.space_key.as_deref()),
            ("space_type", args.space_type.as_deref()),
        ]);
        vec![PromptMessage::new_text(
            Role::User,
            format!(
                "{header}\n\n{}",
                include_str!("content/space_provisioning.md")
            ),
        )]
    }

    #[prompt(
        name = "confluence_workflow_user_lifecycle",
        description = "Onboard (check-then-create, group membership, permissions, watch) or \
                        offboard (disable, remove from groups, revoke permissions) a user -- \
                        an explicit fork on direction."
    )]
    async fn confluence_workflow_user_lifecycle_prompt(
        &self,
        Parameters(args): Parameters<UserLifecycleArgs>,
    ) -> Vec<PromptMessage> {
        let header = render_context_header(&[
            ("username", args.username.as_deref()),
            ("lifecycle_stage", args.lifecycle_stage.as_deref()),
            ("space_key", args.space_key.as_deref()),
        ]);
        vec![PromptMessage::new_text(
            Role::User,
            format!("{header}\n\n{}", include_str!("content/user_lifecycle.md")),
        )]
    }
}
